DROP TABLE IF EXISTS Player;
DROP TABLE IF EXISTS Buff;
DROP TABLE IF EXISTS Country;

CREATE TABLE Player (
username VARCHAR(15) PRIMARY KEY,
password NUMERIC,
wins INTEGER UNSIGNED,
losses INTEGER UNSIGNED,
draws INTEGER UNSIGNED,
elo INTERGER UNSIGNED
);

CREATE TABLE Buff (
id INTEGER PRIMARY KEY AUTOINCREMENT,
type VARCHAR(20),
priority INTEGER UNSIGNED,
hash NUMERIC,
playerID VARCHAR(15),
FOREIGN KEY (playerID) REFERENCES Player(id)
);

CREATE TABLE Country (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name VARCHAR(15),
playerID VARCHAR(15),
towns INTEGER UNSIGNED,
type VARCHAR(15),
production INTEGER UNSIGNED,
priority INTEGER UNSIGNED,
hash NUMERIC,
FOREIGN KEY (playerID) REFERENCES Player(id)
);
